M48
; DRILL file KiCad 10.0.4 date 2026-08-28T17:36:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-28T17:36:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X158.06Y-53.005
X163.84Y-53.005
T2
X156.95Y-91.0
X164.55Y-91.0
M30
