M48
; DRILL file KiCad 10.0.5-10.0.5~ubuntu24.04.1 date 2026-08-26T19:31:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-26T19:31:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5-10.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X158.06Y-53.005
X163.84Y-53.005
T2
X156.95Y-91.0
X164.55Y-91.0
M30
